# -*- coding: utf-8 -*-
"""Krutik PDM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ylx5VIByRfrvRlp9iiFrRpu6F19XJk_H

# **Importing the necessary data analysis libraries**
"""

# ============================================
# IMPORTING ALL REQUIRED LIBRARIES
# PDM CW2 - Employee Attrition Prediction
# ============================================


# -----------------------------
# Data Handling Libraries
# -----------------------------

import pandas as pd
import numpy as np

# -----------------------------
# Data Visualisation Libraries
# -----------------------------

import matplotlib.pyplot as plt
import seaborn as sns

# -----------------------------
# Data Pre-processing Libraries
# -----------------------------

from sklearn.preprocessing import (LabelEncoder,StandardScaler)

# -----------------------------
# Dataset Splitting Library
# -----------------------------

from sklearn.model_selection import train_test_split

# -----------------------------
# Machine Learning Models
# -----------------------------

from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression

# -----------------------------
# Model Evaluation Metrics
# -----------------------------

from sklearn.metrics import (accuracy_score,classification_report,confusion_matrix,
    log_loss,roc_auc_score,roc_curve)

# -----------------------------
# Warning Management
# -----------------------------

import warnings
warnings.filterwarnings("ignore")

"""# **Load HR Operations Dataset**"""

# Load HR dataset
hr_df = pd.read_csv("/content/hr_op.csv")

# Display first 5 records
hr_df.head()

hr_df.columns

"""# **Load Personal Operations Dataset**"""

# Load Personal dataset
personal_df = pd.read_excel("/content/personal_op.xlsx")

# Display first 5 records
personal_df.head()

personal_df_clean = personal_df.drop(
    "attrition",
    axis=1
)

"""# **Check Dataset Dimensions**"""

print("HR Dataset Shape:")
print(hr_df.shape)

print("\nPersonal Dataset Shape:")
print(personal_df_clean.shape)

"""# **Combine Both Datasets Using employee_id Only**"""

# Merge datasets using employee_id

employee_df = pd.merge(hr_df,personal_df_clean,on="employee_id",how="inner")
employee_df.head()

"""# **Check Final Combined Dataset**"""

employee_df.shape

employee_df.info()

"""# **Check Duplicate Records After Merge**"""

employee_df.duplicated().sum()

"""# **Check Missing Values After Merge**"""

employee_df.isnull().sum()

employee_df = employee_df.dropna()

employee_df.isnull().sum()

employee_df.describe()

"""# **Target Variable Distribution**"""

plt.figure(figsize=(8,5))
sns.countplot(x="attrition",data=employee_df)
plt.title("Employee Attrition Distribution")

plt.xlabel("Attrition (0 = Stayed, 1 = Left)")

plt.ylabel("Number of Employees")

plt.show()

"""# **Descriptve Analysis**

## **Distribution of Employees by Department**
"""

# Employee count by department

department_count = (
    employee_df["department"]
    .value_counts()
)

department_count

plt.figure(figsize=(8,5))

ax = sns.barplot(
    x=department_count.index,
    y=department_count.values,
    palette="viridis"
)


plt.title(
    "Distribution of Employees by Department",
    fontsize=14
)

plt.xlabel("Department")

plt.ylabel("Number of Employees")


# Data labels

for container in ax.containers:
    ax.bar_label(container)


plt.xticks(rotation=45)

plt.show()

"""# **Distribution of Employees by Job Role**"""

jobrole_count = (
    employee_df["job_role"]
    .value_counts()
)


jobrole_count

plt.figure(figsize=(9,5))


ax = sns.barplot(
    x=jobrole_count.index,
    y=jobrole_count.values,
    palette="Spectral"
)


plt.title(
    "Distribution of Employees by Job Role",
    fontsize=14
)


plt.xlabel("Job Role")

plt.ylabel("Number of Employees")


for container in ax.containers:
    ax.bar_label(container)


plt.xticks(rotation=45)

plt.show()

"""# **Average Tenure Years of Employees**"""

average_tenure = employee_df["tenure_years"].mean()


print(
    "Average Tenure:",
    round(average_tenure,2),
    "years"
)

plt.figure(figsize=(8,5))


sns.histplot(
    employee_df["tenure_years"],
    bins=20,
    kde=True,
    color="teal"
)


plt.title(
    "Distribution of Employee Tenure Years"
)


plt.xlabel(
    "Tenure Years"
)


plt.ylabel(
    "Employee Count"
)


plt.show()

"""## **Average Monthly Income by Department**"""

income_department = (
    employee_df
    .groupby("department")["monthly_income"]
    .mean()
    .sort_values(ascending=False)
)


income_department

plt.figure(figsize=(10,5))


ax = sns.barplot(
    x=income_department.index,
    y=income_department.values,
    palette="coolwarm"
)


plt.title(
    "Average Monthly Income by Department"
)


plt.xlabel(
    "Department"
)


plt.ylabel(
    "Average Monthly Income"
)


for container in ax.containers:
    ax.bar_label(
        container,
        fmt="%.0f"
    )


plt.xticks(rotation=45)


plt.show()

"""# **Average Overtime Hours (Stayed vs Left Employees)**"""

overtime_attrition = (
    employee_df
    .groupby("attrition")
    ["overtime_hours"]
    .mean()
)

overtime_attrition

overtime_attrition.index = [
    "Stayed",
    "Left"
]


overtime_attrition

plt.figure(figsize=(7,5))


ax = sns.barplot(
    x=overtime_attrition.index,
    y=overtime_attrition.values,
    palette="husl"
)


plt.title(
    "Average Overtime Hours: Stayed vs Left Employees"
)


plt.xlabel(
    "Employee Status"
)


plt.ylabel(
    "Average Overtime Hours"
)


for container in ax.containers:
    ax.bar_label(
        container,
        fmt="%.2f"
    )


plt.show()

"""# **Distribution of Monthly Income**"""

employee_df["monthly_income"].describe()

plt.figure(figsize=(8,5))


sns.histplot(
    employee_df["monthly_income"],
    bins=30,
    kde=True,
    color="purple"
)


plt.title(
    "Distribution of Monthly Income"
)


plt.xlabel(
    "Monthly Income"
)


plt.ylabel(
    "Employee Frequency"
)


plt.show()

"""# **Distribution of Ethnicity**"""

ethnicity_count = (
    employee_df["ethnicity"]
    .value_counts()
)


ethnicity_count

plt.figure(figsize=(8,5))


ax = sns.barplot(
    x=ethnicity_count.index,
    y=ethnicity_count.values,
    palette="cubehelix"
)


plt.title(
    "Distribution of Employee Ethnicity"
)


plt.xlabel(
    "Ethnicity"
)


plt.ylabel(
    "Number of Employees"
)


for container in ax.containers:
    ax.bar_label(container)


plt.xticks(rotation=45)

plt.show()

"""# **Average Monthly Income by Gender**"""

income_gender = (
    employee_df
    .groupby("gender")
    ["monthly_income"]
    .mean()
)


income_gender

plt.figure(figsize=(7,5))


ax = sns.barplot(
    x=income_gender.index,
    y=income_gender.values,
    palette="copper"
)


plt.title(
    "Average Monthly Income by Gender"
)


plt.xlabel(
    "Gender"
)


plt.ylabel(
    "Average Monthly Income"
)


for container in ax.containers:
    ax.bar_label(
        container,
        fmt="%.0f"
    )


plt.show()

"""# **Marital Status Distribution**"""

marital_count = (
    employee_df["marital_status"]
    .value_counts()
)


marital_count

plt.figure(figsize=(7,5))


ax = sns.barplot(
    x=marital_count.index,
    y=marital_count.values,
    palette="hot"
)


plt.title(
    "Distribution of Employee Marital Status"
)


plt.xlabel(
    "Marital Status"
)


plt.ylabel(
    "Number of Employees"
)


for container in ax.containers:
    ax.bar_label(container)


plt.show()

"""# **Disability Status Distribution**"""

disability_count = (
    employee_df["disability_status"]
    .value_counts()
)


disability_count

plt.figure(figsize=(7,5))


ax = sns.barplot(
    x=disability_count.index,
    y=disability_count.values,
    palette="rocket"
)


plt.title(
    "Distribution of Disability Status"
)


plt.xlabel(
    "Disability Status"
)


plt.ylabel(
    "Number of Employees"
)


for container in ax.containers:
    ax.bar_label(container)


plt.show()

"""# **Relationship Between Overtime Hours, Monthly Income and Work-Life Balance**"""

relationship_data = employee_df[
[
    "overtime_hours",
    "monthly_income",
    "work_life_balance_score"
]
]


relationship_data.corr()

plt.figure(figsize=(10,6))


sns.heatmap(
    relationship_data.corr(),
    annot=True,
    cmap="RdPu",
    linewidths=0.5
)


plt.title(
    "Relationship Between Overtime, Income and Work-Life Balance"
)


plt.show()

"""# **Data Preparation**

## **Remove Employee ID Column**
"""

# Remove ID column
model_df = employee_df.drop("employee_id",axis=1)

"""## **Separate Features and Target Variable**"""

# Independent variables

X = model_df.drop(
    "attrition",
    axis=1
)

# Target variable

y = model_df["attrition"]

"""# **Identify Categorical Columns**"""

categorical_columns = X.select_dtypes(
    include="object"
).columns

"""# **Encode Categorical Variables**"""

encoder = LabelEncoder()


for column in categorical_columns:
    # Convert the column to string type to ensure uniform data type
    X[column] = X[column].astype(str)
    X[column] = encoder.fit_transform(
        X[column]
    )

"""# **Feature Scaling**"""

scaler = StandardScaler()


X_scaled = scaler.fit_transform(X)


X_scaled = pd.DataFrame(
    X_scaled,
    columns=X.columns
)

"""# **Train-Test Split**"""

X_train, X_test, y_train, y_test = train_test_split(

    X_scaled,
    y,

    test_size=0.20,

    random_state=42,

    stratify=y
)

"""================================
# **MODEL 1: NAIVE BAYES**
================================
"""

nb_model = GaussianNB()

nb_model.fit(X_train,y_train)

nb_prediction = nb_model.predict(X_test)

nb_probability = nb_model.predict_proba(X_test)[:,1]

nb_accuracy = accuracy_score(
    y_test,
    nb_prediction
)


print(
    "Naive Bayes Accuracy:",
    round(nb_accuracy,4)
)

print(
    "Naive Bayes Classification Report"
)


print(
    classification_report(
        y_test,
        nb_prediction
    )
)

nb_logloss = log_loss(
    y_test,
    nb_probability
)


print(
    "Naive Bayes Log Loss:",
    round(nb_logloss,4)
)

nb_cm = confusion_matrix(
    y_test,
    nb_prediction
)


nb_cm

plt.figure(figsize=(8,5))


sns.heatmap(
    nb_cm,
    annot=True,
    fmt="d",
    cmap="PuOr"
)


plt.title(
    "Naive Bayes Confusion Matrix"
)


plt.xlabel(
    "Predicted"
)


plt.ylabel(
    "Actual"
)


plt.show()

nb_auc = roc_auc_score(
    y_test,
    nb_probability
)


print(
    "Naive Bayes ROC-AUC:",
    round(nb_auc,4)
)

fpr_nb, tpr_nb, threshold_nb = roc_curve(
    y_test,
    nb_probability
)


plt.figure(figsize=(7,5))


plt.plot(
    fpr_nb,
    tpr_nb,
    label=f"Naive Bayes AUC={nb_auc:.3f}"
)


plt.plot(
    [0,1],
    [0,1],
    linestyle="--"
)


plt.title(
    "Naive Bayes ROC Curve"
)


plt.xlabel(
    "False Positive Rate"
)


plt.ylabel(
    "True Positive Rate"
)


plt.legend()


plt.show()

"""=================================
# **MODEL 2: LOGISTIC REGRESSION**
=================================
"""

lr_model = LogisticRegression(
    max_iter=1000
)


lr_model.fit(
    X_train,
    y_train
)

lr_prediction = lr_model.predict(
    X_test
)


lr_probability = lr_model.predict_proba(
    X_test
)[:,1]

lr_accuracy = accuracy_score(
    y_test,
    lr_prediction
)


print(
    "Logistic Regression Accuracy:",
    round(lr_accuracy,4)
)

print(
    "Logistic Regression Classification Report"
)


print(
    classification_report(
        y_test,
        lr_prediction
    )
)

lr_logloss = log_loss(
    y_test,
    lr_probability
)


print(
    "Logistic Regression Log Loss:",
    round(lr_logloss,4)
)

lr_cm = confusion_matrix(
    y_test,
    lr_prediction
)


lr_cm

plt.figure(figsize=(8,5))


sns.heatmap(
    lr_cm,
    annot=True,
    fmt="d",
    cmap="RdBu"
)


plt.title(
    "Logistic Regression Confusion Matrix"
)


plt.xlabel(
    "Predicted"
)


plt.ylabel(
    "Actual"
)


plt.show()

lr_auc = roc_auc_score(
    y_test,
    lr_probability
)


print(
    "Logistic Regression ROC-AUC:",
    round(lr_auc,4)
)

fpr_lr, tpr_lr, threshold_lr = roc_curve(
    y_test,
    lr_probability
)


plt.figure(figsize=(7,5))


plt.plot(
    fpr_lr,
    tpr_lr,
    label=f"Logistic Regression AUC={lr_auc:.3f}"
)


plt.plot(
    [0,1],
    [0,1],
    linestyle="--"
)


plt.title(
    "Logistic Regression ROC Curve"
)


plt.xlabel(
    "False Positive Rate"
)


plt.ylabel(
    "True Positive Rate"
)


plt.legend()


plt.show()

"""# **Model Comparison**"""

model_comparison = pd.DataFrame(
{
    "Model":
    [
        "Naive Bayes",
        "Logistic Regression"
    ],

    "Accuracy":
    [
        nb_accuracy,
        lr_accuracy
    ],

    "Log Loss":
    [
        nb_logloss,
        lr_logloss
    ],

    "ROC-AUC":
    [
        nb_auc,
        lr_auc
    ]
}
)


model_comparison